projects:
  - '*':
    - project_visibility: 'internal'
    - project_pages_access_level: 'private'
    - project_security_and_compliance_enabled: True
    - project_approvals_before_merge: 1
    - project_push_rules_unsigned_commits: True
    - project_push_rules_comitter_check: True
    - project_protected_branches: True
    - project_access_tokens: False
    - project_deploy_tokens: False
    - project_deploy_keys: False
    - project_pipeline: True
    - project_pipeline_stages: None
    - project_pipeline_image: None
    - project_codeowners: True
    - project_shared_runners_enabled: False
    - project_runners_shared: False
    - project_runners_notshared: True